allowBuilds:
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - "@astrojs/starlight@0.41.2"
  - "@img/sharp-darwin-arm64@0.35.3"
  - "@img/sharp-darwin-x64@0.35.3"
  - "@img/sharp-freebsd-wasm32@0.35.3"
  - "@img/sharp-linux-arm64@0.35.3"
  - "@img/sharp-linux-arm@0.35.3"
  - "@img/sharp-linux-ppc64@0.35.3"
  - "@img/sharp-linux-riscv64@0.35.3"
  - "@img/sharp-linux-s390x@0.35.3"
  - "@img/sharp-linux-x64@0.35.3"
  - "@img/sharp-linuxmusl-arm64@0.35.3"
  - "@img/sharp-linuxmusl-x64@0.35.3"
  - "@img/sharp-wasm32@0.35.3"
  - "@img/sharp-webcontainers-wasm32@0.35.3"
  - "@img/sharp-win32-arm64@0.35.3"
  - "@img/sharp-win32-ia32@0.35.3"
  - "@img/sharp-win32-x64@0.35.3"
  - sharp@0.35.3
